# -*- coding: utf-8 -*-
"""cifar10_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KXzdoDuzEACdI1wYcLgEvdiYPZLfQKmc

# Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Import Libraries"""